version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:example@db:5432/postgres
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: sh -c "npx prisma generate && npx prisma migrate dev --name init && npm run dev"
